name: Docker Image

on:
  push:
    branches: 
      - "main"  # Ejecutará el flujo cuando se haga push a la rama main

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout del código fuente
    - name: Checkout code
      uses: actions/checkout@v4

    # 2. Log in en DockerHub
    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # 3. Construir y subir la imagen Docker a DockerHub
    - name: Build and push Docker image
      run: |
        docker build . --file Dockerfile --tag epgarzonr/index:latest
        docker push epgarzonr/index:latest

  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
    # 1. Conectar a EC2 y desplegar la aplicación
    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        port: 22  # Cambié el puerto de 80 a 22
        script: |
          # Actualizar y configurar Docker
          sudo apt update -y
          sudo apt install -y docker
          sudo service docker start
          sudo usermod -a -G docker ec2-user

          # Descargar la imagen Docker desde DockerHub
          sudo docker pull epgarzonr/index:latest

          # Detener cualquier contenedor existente y desplegar el nuevo
          sudo docker ps -q --filter "name=index" | grep -q . && docker stop index && docker rm index || true
          sudo docker run -d --name index -p 80:80 epgarzonr/index:latest
